### ISSUE TITLE
load library  Error

### ISSUE THREAD

**Issue by SelenaWong** [jessieeeee/SimpleOne#2]
09-10 14:40:22.537: E/AndroidRuntime(32222): java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.jessie.simpleone/lib-main/libgnustl_shared.so" is 32-bit instead of 64-bit
09-10 14:40:22.537: E/AndroidRuntime(32222): 	at java.lang.Runtime.load0(Runtime.java:914)
09-10 14:40:22.537: E/AndroidRuntime(32222): 	at java.lang.System.load(System.java:1508)
09-10 14:40:22.537: E/AndroidRuntime(32222): 	at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:71)
09-10 14:40:22.537: E/AndroidRuntime(32222): 	at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:42)
09-10 14:40:22.537: E/AndroidRuntime(32222): 	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:299)
09-10 14:40:22.537: E/AndroidRuntime(32222): 	at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:65)
09-10 14:40:22.537: E/AndroidRuntime(32222): 	at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:42)
09-10 14:40:22.537: E/AndroidRuntime(32222): 	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:299)
09-10 14:40:22.537: E/AndroidRuntime(32222): 	at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:65)
09-10 14:40:22.537: E/AndroidRuntime(32222): 	at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:42)
09-10 14:40:22.537: E/AndroidRuntime(32222): 	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:299)
09-10 14:40:22.537: E/AndroidRuntime(32222): 	at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:65)
09-10 14:40:22.537: E/AndroidRuntime(32222): 	at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:42)
09-10 14:40:22.537: E/AndroidRuntime(32222): 	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:299)
09-10 14:40:22.537: E/AndroidRuntime(32222): 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:247)
09-10 14:40:22.537: E/AndroidRuntime(32222): 	at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:17)
09-10 14:40:22.537: E/AndroidRuntime(32222): 	at com.facebook.react.bridge.Inspector.<clinit>(Inspector.java:17)
09-10 14:40:22.537: E/AndroidRuntime(32222): 	at com.facebook.react.bridge.Inspector.isSupported(Inspector.java:25)
09-10 14:40:22.537: E/AndroidRuntime(32222): 	at com.facebook.react.devsupport.DevSupportManagerImpl.showDevOptionsDialog(DevSupportManagerImpl.java:386)
09-10 14:40:22.537: E/AndroidRuntime(32222): 	at com.jessie.simpleone.MainActivity.onCreate(MainActivity.java:58)

**Comment by jessieeeee** [comment]
Are you running on a 64-bit phone?

**Comment by jessieeeee** [comment]
I have commit code, you can pull it and try again
